// <auto-generated />
namespace LiveyServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class adddateobjtoitems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddateobjtoitems));
        
        string IMigrationMetadata.Id
        {
            get { return "202004031320431_add date obj to items"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
