// <auto-generated />
namespace LiveyServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SubCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SubCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202004022042340_SubCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
